lib/glimesh_web/router.ex
    plug Plug.Parsers, parsers: [:urlendoded]
  end

  if Mix.env() in [:dev, :test] do
    scope "/" do
      pipe_through :browser

      forward "/sent_emails", Bamboo.SentEmailViewerPlug
    end
  end

  scope "/api/oauth", GlimeshWeb do
    pipe_through :oauth

    post "/token", OauthController, :token
    post "/revoke", OauthController, :revoke
    post "/introspect", OauthController, :introspect
  end

  scope "/api/webhook", GlimeshWeb do
    pipe_through :api

    # post "/stripe", WebhookController, :stripe
    post "/taxidpro", WebhookController, :taxidpro
  end

  scope "/api/graph" do
    pipe_through :graphql_alpha_api

    forward "/", Glimesh.Api.GraphiQLPlug,
      schema: Glimesh.Api.Schema,
      socket: GlimeshWeb.GraphApiSocket,
      default_url: {__MODULE__, :graph_default_url},
      socket_url: {__MODULE__, :graph_socket_url},
      interface: :playground,
      analyze_complexity: true,
      max_complexity: 500
  end

  scope "/api" do
    pipe_through :graphql

    forward "/", Absinthe.Plug.GraphiQL,
      schema: Glimesh.OldSchema,
      socket: GlimeshWeb.OldApiSocket,
      default_url: {__MODULE__, :graphiql_default_url},
      socket_url: {__MODULE__, :graphiql_socket_url}
  end

  ## Authentication routes
  scope "/", GlimeshWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    post "/users/log_in_tfa", UserSessionController, :tfa
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", GlimeshWeb do
    pipe_through [:browser, :require_authenticated_user]

    live "/platform_subscriptions", PlatformSubscriptionLive.Index, :index

    get "/users/social/twitter", UserSocialController, :twitter
    delete "/users/social/disconnect/:platform", UserSocialController, :disconnect

    get "/users/payments", UserPaymentsController, :index
    post "/users/payments/setup", UserPaymentsController, :setup
    get "/users/payments/taxes", UserPaymentsController, :taxes
    get "/users/payments/taxes_pending", UserPaymentsController, :taxes_pending
    get "/users/payments/connect", UserPaymentsController, :connect
    put "/users/payments/delete_default_payment", UserPaymentsController, :delete_default_payment

    get "/users/settings/profile", UserSettingsController, :profile
    get "/users/settings/stream", UserSettingsController, :stream

    get "/users/settings/channel_statistics", UserSettingsController, :channel_statistics
    get "/users/settings/addons", UserSettingsController, :addons
    get "/users/settings/emotes", UserSettingsController, :emotes
    get "/users/settings/upload_emotes", UserSettingsController, :upload_emotes
    get "/users/settings/hosting", UserSettingsController, :hosting

    put "/users/settings/create_channel", UserSettingsController, :create_channel
    put "/users/settings/delete_channel", UserSettingsController, :delete_channel
    get "/users/settings/preference", UserSettingsController, :preference
    put "/users/settings/preference", UserSettingsController, :update_preference
    put "/users/settings/update_profile", UserSettingsController, :update_profile
    put "/users/settings/update_channel", UserSettingsController, :update_channel
    get "/users/settings/notifications", UserSettingsController, :notifications

    get "/users/settings/security", UserSecurityController, :index
    put "/users/settings/update_password", UserSecurityController, :update_password
    put "/users/settings/update_email", UserSecurityController, :update_email
    get "/users/settings/confirm_email/:token", UserSecurityController, :confirm_email
    put "/users/settings/update_tfa", UserSecurityController, :update_tfa
    get "/users/settings/get_tfa", UserSecurityController, :get_tfa
    get "/users/settings/tfa_registered", UserSecurityController, :tfa_registered

    put "/users/settings/applications/:id/rotate", UserApplicationsController, :rotate
    resources "/users/settings/applications", UserApplicationsController

    resources "/users/settings/authorizations", UserAuthorizedAppsController,
      only: [:index, :delete],
      param: "id"

    get "/oauth/authorize", OauthController, :authorize
    post "/oauth/authorize", OauthController, :process_authorize
  end

  scope "/", GlimeshWeb do
    pipe_through [:browser, :require_authenticated_user, :require_user_has_channel]

    post "/users/settings/channel/mods/ban_user",
         ChannelModeratorController,
         :ban_user

    delete "/users/settings/channel/mods/unban_user/:username",
           ChannelModeratorController,
           :unban_user

    resources "/users/settings/channel/mods", ChannelModeratorController
  end

  scope "/admin", GlimeshWeb do
    pipe_through [:browser, :require_admin_user]

    import Phoenix.LiveDashboard.Router

    live_dashboard "/phoenix/dashboard", metrics: GlimeshWeb.Telemetry, ecto_repos: [Glimesh.Repo]

    live "/categories", Admin.CategoryLive.Index, :index
    live "/categories/new", Admin.CategoryLive.Index, :new
    live "/categories/:id/edit", Admin.CategoryLive.Index, :edit

    live "/categories/:id", Admin.CategoryLive.Show, :show
    live "/categories/:id/show/edit", Admin.CategoryLive.Show, :edit

    live "/tags", Admin.TagLive.Index, :index
    live "/tags/new", Admin.TagLive.Index, :new
    live "/tags/:id/edit", Admin.TagLive.Index, :edit
  end

  scope "/gct", GlimeshWeb do
    pipe_through [:browser, :require_gct_user]

    get "/", GctController, :index
    get "/me", GctController, :edit_self
    get "/unauthorized", GctController, :unauthorized

    # Lookup scopes
    get "/lookup/user", GctController, :username_lookup
    get "/lookup/channel", GctController, :channel_lookup
    get "/lookup/channel/:channel_id/chat", GctController, :channel_chat_log
    get "/lookup/user/:user_id/chat", GctController, :user_chat_log

    # Editing profile scopes
    get "/edit/profile/:username", GctController, :edit_user_profile
    put "/edit/profile/:username/update", GctController, :update_user_profile

    # Editing user scopes
    get "/edit/:username", GctController, :edit_user
    put "/edit/:username/update", GctController, :update_user

    # Editing channel scopes
    get "/edit/channel/:channel_id", GctController, :edit_channel
    post "/edit/channel/:channel_id/shutdown", GctController, :shutdown_channel
    put "/edit/channel/:channel_id/update", GctController, :update_channel
    put "/edit/channel/:channel_id/delete", GctController, :delete_channel

    # Audit log
    get "/audit-log", GctController, :audit_log

    # Emote scopes
    get "/global-emotes", GctController, :global_emotes
    get "/review-emotes", GctController, :review_emotes

    # Categories and subcategories and tags and probably more
  end

  scope "/", GlimeshWeb do
    pipe_through [:browser, :require_events_team_user]

    live "/eventsteam", EventsTeam.EventsAdminLive, :index
  end

  scope "/", GlimeshWeb do
    pipe_through [:browser]

    get "/about", AboutController, :index
    get "/about/streaming", AboutController, :streaming
    get "/about/team", AboutController, :team
    get "/about/mission", AboutController, :mission
    get "/about/alpha", AboutController, :alpha
    get "/about/faq", AboutController, :faq
    get "/about/privacy", AboutController, :privacy
    get "/about/terms", AboutController, :terms
    get "/about/conduct", AboutController, :conduct
    get "/about/credits", AboutController, :credits
    get "/about/dmca", AboutController, :dmca

    live "/about/open-data", About.OpenDataLive, :index
    live "/about/open-data/subscriptions", About.OpenDataLive, :subscriptions
    live "/about/open-data/streams", About.OpenDataLive, :streams

    get "/events", EventsTeamController, :events_team

    get "/blog", BlogMigrationController, :redirect_blog
    get "/blog/:slug", BlogMigrationController, :redirect_post

    live "/", HomepageLive, :index
    live "/streams", StreamsLive.Index, :index
    live "/streams/following", StreamsLive.Following, :index
    live "/streams/:category", StreamsLive.List, :index

    live "/users", UserLive.Index, :index

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :confirm

    post "/quick_preferences", QuickPreferenceController, :update_preference

    # Short Links
    get "/s/event-form", ShortLinkController, :event_form
    get "/s/discord", ShortLinkController, :community_discord

    # This must be the last route
    live "/:username", UserLive.Stream, :index
    live "/:username/support", UserLive.Stream, :support
    live "/:username/support/:tab", UserLive.Stream, :support
    live "/:username/profile", UserLive.Profile, :index
    live "/:username/profile/followers", UserLive.Followers, :followers
    live "/:username/profile/following", UserLive.Followers, :following
    live "/:username/chat", ChatLive.PopOut, :index
  end

  alias GlimeshWeb.Router.Helpers, as: Routes

  def graphiql_default_url(conn) do
    Routes.url(conn) <> "/api"
  end

  def graphiql_socket_url(conn) do
    (Routes.url(conn) <> "/api/socket")
    |> String.replace("http", "ws")
    |> String.replace("https", "wss")
  end

  def graph_default_url(conn) do
    Routes.url(conn) <> "/api/graph"
  end

  def graph_socket_url(conn) do
    (Routes.url(conn) <> "/api/graph/socket")
    |> String.replace("http", "ws")

lib/glimesh_web/controllers/about_controller.ex
defmodule GlimeshWeb.AboutController do
  use GlimeshWeb, :controller

  plug :put_layout, "about.html"

  def index(conn, _param) do
    render(conn, "index.html", page_title: format_page_title(gettext("About Glimesh")))
  end

  def streaming(conn, _param) do
    render(conn, "streaming.html", page_title: format_page_title(gettext("Streaming")))
  end

  def team(conn, _param) do
    users = Glimesh.Accounts.list_team_users()

    render(conn, "team.html",
      page_title: format_page_title(gettext("The Team")),
      users: users
    )
  end

  def mission(conn, _param) do
    render(conn, "mission.html", page_title: format_page_title(gettext("Our Mission")))
  end

  def alpha(conn, _param) do
    render(conn, "alpha.html", page_title: format_page_title(gettext("Alpha")))
  end

  # Other layouts

  def faq(conn, _param) do
    conn
    |> put_layout("text.html")
    |> render("faq.html", page_title: format_page_title(gettext("Frequently Asked Questions")))
  end

  def privacy(conn, _param) do
    conn
    |> put_layout("text.html")
    |> render("privacy.html", page_title: format_page_title(gettext("Privacy & Cookie Policy")))
  end

  def terms(conn, _param) do
    conn
    |> put_layout("text.html")
    |> render("terms.html", page_title: format_page_title(gettext("Terms of Service")))
  end

  def conduct(conn, _param) do
    conn
    |> put_layout("text.html")
    |> render("conduct.html", page_title: format_page_title(gettext("Rules of Conduct")))
  end

  def dmca(conn, _params) do
    conn
    |> put_layout("app.html")
    |> render("dmca.html",
      page_title: format_page_title(gettext("DMCA"))
    )
  end

  def credits(conn, _param) do
    %{
      ftl: ftl_credits,
      node: node_credits,
      elixir: elixir_credits
    } = Glimesh.Credits.get_dependencies()

    founder_subscribers = Glimesh.Payments.list_platform_founder_subscribers()
    supporter_subscribers = Glimesh.Payments.list_platform_supporter_subscribers()

    conn
    |> put_layout("text.html")
    |> render("credits.html",
      page_title: format_page_title(gettext("Credits")),
      ftl_credits: ftl_credits,
      elixir_credits: elixir_credits,
      node_credits: node_credits,
      founder_subscribers: founder_subscribers,
      supporter_subscribers: supporter_subscribers
    )
  end
end

lib/glimesh_web/live/about/open_data_live.ex
defmodule GlimeshWeb.About.OpenDataLive do
  use GlimeshWeb, :live_view

  @impl true
  def mount(_, session, socket) do
    if session["locale"], do: Gettext.put_locale(session["locale"])

    {:ok,
     socket
     |> assign(:chart_data, Jason.encode!(%{}))
     |> assign(:chart_theme, Map.get(session, "site_theme", "dark"))}
  end

  @impl true
  def handle_params(params, _url, socket) do
    {:noreply, apply_action(socket, socket.assigns.live_action, params)}
  end

  defp apply_action(socket, :index, _) do
    socket
    |> put_page_title(gettext("Platform User Growth"))
    |> assign(:chart_data, Glimesh.Charts.PlatformUserGrowth.json())
  end

  defp apply_action(socket, :subscriptions, _) do
    socket
    |> put_page_title(gettext("Recurring Subscriptions"))
    |> assign(:chart_data, Glimesh.Charts.RecurringSubscriptions.json())
  end

  defp apply_action(socket, :streams, _) do
    socket
    |> put_page_title(gettext("Live Streams"))
    |> assign(:chart_data, Glimesh.Charts.LiveStreams.json())
  end
end

lib/glimesh_web/views/about_view.ex
defmodule GlimeshWeb.AboutView do
  use GlimeshWeb, :view
end

lib/glimesh_web/templates/about/alpha.html.eex
<div class="jumbotron jumbotron-fluid jumbotron-glimesh d-flex align-items-center">
    <div class="container">
        <h1 class="display-4 text-center"><%= gettext("Alpha") %></h1>
    </div>
</div>

<div class="container">

    <h2 class="text-white"><span class="text-color-alpha">Alpha</span> Features</h2>

    <div class="row mt-2 mb-4">
        <div class="col mb-2">
            <div class="card h-100">
                <h5 class="card-header bg-primary text-center rounded-lg py-4 text-white" style="margin:-1px"><%= gettext("Profiles") %></h5>
                <div class="d-flex align-items-center card-body p-3">
                    <p class="card-text text-center"><%= gettext("Start right away with securing your profile and then make it yours! With loads of customizable features, you can really edit and bring your profiles to life to help show people who you are and what you are about!") %></p>
                </div>
            </div>
        </div>
        <div class="col mb-2">
            <div class="card h-100">
                <h5 class="card-header bg-primary text-center rounded-lg py-4 text-white" style="margin:-1px"><%= gettext("Streaming") %></h5>
                <div class="d-flex align-items-center card-body p-3">
                    <p class="card-text text-center"><%= gettext("You'll be able to create your stream, go live, and begin growing your communities. Interacting with them will be a whole lot easier with the FTL streaming technology – they will be able to view your stream in real-time!") %></p>
                </div>
            </div>
        </div>
        <div class="col mb-2">
            <div class="card h-100">
                <h5 class="card-header bg-primary text-center rounded-lg py-4 text-white" style="margin:-1px"><%= gettext("Subscriptions") %></h5>
                <div class="d-flex align-items-center card-body p-3">
                    <p class="card-text text-center"><%= gettext("Subscription buttons will be available, with payouts, and you will not need to meet any viewership requirements for them. During early phases, this will only be available to limited countries.") %></p>
                </div>
            </div>
        </div>
        <div class="col mb-2">
            <div class="card h-100">
                <h5 class="card-header bg-primary text-center rounded-lg py-4 text-white" style="margin:-1px"><%= gettext("Live Events") %></h5>
                <div class="d-flex align-items-center card-body p-3">
                    <p class="card-text text-center"><%= gettext("Our Glimesh Community Team will be hosting live events filled with content from all of our various categories. Keep an eye out on our Twitter, for now, to stay up to date with these.") %></p>
                </div>
            </div>
        </div>
        <div class="col mb-2">
            <div class="card h-100">
                <h5 class="card-header bg-primary text-center rounded-lg py-4 text-white" style="margin:-1px"><%= gettext("More!") %></h5>
                <div class="d-flex align-items-center card-body p-3">
                    <p class="card-text text-center"><%= gettext("Remember, this is just the Alpha! We are excited to continue to develop features you expect while still continuing to innovate on brand new ideas. You can check out our Alpha Roadmap for planned features.") %><br>
                        <a href="https://glimesh.tv/blog/2020-08-13-glimesh-alpha-roadmap"><%= gettext("Alpha Roadmap") %></a></p>
                </div>
            </div>
        </div>
    </div>


    <h2 class="text-white"><span class="text-color-alpha">Alpha</span> Support</h2>

    <div class="card mt-2">
        <h3 class="card-header bg-primary text-center rounded-lg py-4 text-white"><%= gettext("What to Expect") %></h3>
        <div class="card-body">
            <p class="card-text text-center"><%= gettext("We are very excited to be launching the Alpha version of Glimesh and we're proud to say that all of our alpha features will be available to everyone! During this very early phase, we want to set expectations correctly. You can expect that we'll have issues, bugs, and even downtime early on but we will continue to improve and strive for excellence. We invite everyone in early to help us find these issues, to help us create new products, and to continue growing Glimesh into the best platform it can be. We encourage everyone to try new things on the platform and to report issues when you see them! If you need any support or help along the way, we'll be there for you.") %></p>
        </div>
    </div>

    <div class="card mt-4">
        <h3 class="card-header bg-primary text-center rounded-lg py-4 text-white"><%= gettext("Help Us Improve") %></h3>
        <div class="card-body card-glimfamily">
            <div class="row justify-content-md-center">
                <div class="col-md-7">
                    <p><%= gettext("As explained, we know there are going to be bugs and issues that users may experience within this Alpha version of our platform, but we are prepared! We have an amazing team that is ready to triage, fix, and help resolve any issues you may face. Our Discord is the main source of most of our questions, suggestions, and bug reports and you can find details on how to navigate it below!") %></p>

                    <h4><%= gettext("What if I have a question?") %></h4>
                    <p><%= gettext("Really easy! You simply need to join our Discord and locate the channel named #questions. After you've fully written out your question, send it and we'll help you out as soon as possible.") %></p>

                    <h4><%= gettext("How can I make a suggestion?") %></h4>
                    <p><%= gettext("We are always looking to improve and our platform is built on your ideas! Our #suggestions channel gives you an easy place to post any ideas you have or suggestions on how we could do things differently.") %></p>

                    <h4><%= gettext("How do I report a bug?") %></h4>
                    <p><%= gettext("The #bugs channel is the first place bugs should be reported. Our team will triage them, and file them to their appropriate places. When you are submitting a bug, it helps to provide any screenshots or clips you have, but please be sure not to leak your private information. If you have a issue with something sensitive, email support@glimesh and we'll try to reach back out to you when the bug is resolved.") %></p>
                </div>
                <div class="col-md-3 text-center">
                    <img src="/images/homepage/discord.webp" alt="Screenshot of our Discord for reference" class="rounded img-fluid">
                </div>
            </div>
            <div class="text-center mt-4 mb-4">
                <%= link gettext("Join Our Discord"), to: "https://glimesh.tv/s/discord", class: "btn btn-primary" %>
            </div>
        </div>
    </div>



    <div class="row mt-4 mb-4">
        <div class="col-md-6">
            <div class="card h-100">
                <h5 class="card-header bg-primary text-center rounded-lg py-4 text-white"><%= gettext("Useful Documents") %></h5>
                <div class="card-body">
                    <h4><%= gettext("Get up to speed with our Terms of Service!") %></h4>
                    <p><%= gettext("Before you use the platform, you must review our Terms of Service to ensure your streams and content do not violate any of our conditions. The Terms of Service also includes information about your rights and usage of the website.") %></p>

                    <div class="text-center mt-4 mb-4">
                        <%= link gettext("Terms of Service"), to: Routes.about_path(@conn, :terms), class: "btn btn-primary" %>
                    </div>

                    <h4><%= gettext("Review our Rules of Conduct!") %></h4>
                    <p><%= gettext("Our Rules of Conduct is another required reading, especially for streamers! It includes rules and guidelines on the type of content that is appropriate for Glimesh, and violating its guidelines could lead to repercussions.") %></p>

                    <div class="text-center mt-4 mb-4">
                        <%= link gettext("Rules of Conduct"), to: Routes.about_path(@conn, :conduct), class: "btn btn-primary" %>
                    </div>

                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="card h-100">
                <h5 class="card-header bg-primary text-center rounded-lg py-4 text-white"><%= gettext("Additional Support") %></h5>
                <div class="card-body">
                    <h4><%= gettext("Streaming on Glimesh Guide!") %></h4>
                    <p><%= gettext("We have created a useful guide to help get you underway with streaming on Glimesh, regardless of your streaming experience! Remember if you run into any issues, give us a shout and we will always do our best to help!") %></p>

                    <div class="text-center mt-4 mb-4">
                        <%= link gettext("Day One Streamer Guide"), to: "https://glimesh-static-assets.nyc3.digitaloceanspaces.com/2021-glimesh-streaming-guide.pdf", class: "btn btn-primary", target: "_blank" %>
                    </div>

                    <h4><%= gettext("Glimesh Support") %></h4>
                    <p><%= gettext("We also have a support page that can provide you with further information such as FAQs, Account Support, Subscriptions & Payments, and a whole lot more!") %></p>

                    <div class="text-center mt-4 mb-4">
                        <%= link gettext("Glimesh Support Portal"), to: "https://support.glimesh.tv", class: "btn btn-primary", target: "_blank" %>
                    </div>

                </div>
            </div>
        </div>
    </div>

</div>

lib/glimesh_web/templates/about/credits.html.eex
<h1>Glimesh Credits</h1>

<h2><%= gettext("Glimesh Platform Subscribers") %></h2>
<p><%= gettext("Beautiful people who choose to support the platform.") %></p>

<h4><%= gettext("Gold Supporters") %></h4>

<div class="row">
    <%= for sub <- @founder_subscribers do %>

    <div class="col-4 col-md-3 mb-4">
        <%= live_redirect to: Routes.user_profile_path(@conn, :index, sub.user.username) do %>
        <div class="text-md-center">
            <p><%= sub.user.displayname %></p>
            <img src="<%= Glimesh.Avatar.url({sub.user.avatar, sub.user}, :original) %>" alt="<%= sub.user.displayname %>" style="width: 80% !important;" class="img-fluid mb-2 img-avatar">
        </div>
        <% end %>
    </div>

    <% end %>
</div>

<h4><%= gettext("Supporters") %></h4>

<%= for sub <- @supporter_subscribers do %>

<%= live_redirect to: Routes.user_profile_path(@conn, :index, sub.user.username), class: "text-white nowrap" do %>
<img src="<%= Glimesh.Avatar.url({sub.user.avatar, sub.user}, :original) %>" alt="<%= sub.user.displayname %>"
    class="img-avatar" height="20" width="20"> <%= sub.user.displayname %>

<% end %>

<% end %>

<h2><%= gettext("Open Source Libraries") %></h2>
<p><%= gettext("We use numerous open source projects to power Glimesh, and without them this project would never have been possible. This is not a comprehensive list, unfortunately. You can find a full list by browsing our core repositories:") %>
</p>
<nav class="nav nav-fill mt-4 mb-4">
    <a class="nav-item nav-link" href="https://github.com/Glimesh/glimesh.tv" target="_blank">glimesh.tv</a>
    <a class="nav-item nav-link" href="https://github.com/Glimesh/janus-ftl-plugin" target="_blank">janus-ftl-plugin</a>
    <a class="nav-item nav-link" href="https://github.com/Glimesh/janus-ftl-orchestrator"
        target="_blank">janus-ftl-orchestrator</a>
    <a class="nav-item nav-link" href="https://github.com/Glimesh/janus-ftl-player" target="_blank">janus-ftl-player</a>
</nav>

<h4><%= gettext("FTL Libraries") %></h4>
<div class="table-responsive">
    <table class="table">
        <thead>
            <tr>
                <th>Library</th>
                <th>Description</th>
            </tr>
        </thead>
        <tbody>
            <%= for {lib, vsn} <- @ftl_credits do %>
            <tr>
                <td><%= lib %></td>
                <td><%= vsn %></td>
            </tr>
            <% end %>
        </tbody>
    </table>
</div>

<h4><%= gettext("Elixir Libraries") %></h4>
<div class="table-responsive">
    <table class="table">
        <thead>
            <tr>
                <th>Library</th>
                <th>Description</th>
            </tr>
        </thead>
        <tbody>
            <%= for {lib, desc, vsn} <- @elixir_credits do %>
            <tr>
                <td><%= lib %>@<%= vsn %></td>
                <td><%= desc %></td>
            </tr>
            <% end %>
        </tbody>
    </table>
</div>

<h4><%= gettext("NodeJS Libraries") %></h4>
<div class="table-responsive">
    <table class="table">
        <thead>
            <tr>
                <th>Library</th>
                <th>Version</th>
            </tr>
        </thead>
        <tbody>
            <%= for {lib, vsn} <- @node_credits do %>
            <tr>
                <td><%= lib %></td>
                <td><%= vsn %></td>
            </tr>
            <% end %>
        </tbody>
    </table>
</div>

lib/glimesh_web/templates/about/mission.html.eex
<div class="jumbotron jumbotron-fluid jumbotron-glimesh d-flex align-items-center">
    <div class="container">
        <h1 class="display-4 text-center"><%= gettext("Our Mission") %></h1>
    </div>
</div>

<div class="card">
    <div class="card-body">

        <div class="row mt-4 mb-4 justify-content-md-center">
            <div class="col-md-10">
                <blockquote class="blockquote">
                    <p class="mb-0">
                        <%= gettext("Our mission at Glimesh is to create a platform of sustainability, where every content creator has a fair oppourtunity to grow and create an income, while being given simple and powerful tools they can rely on.") %>
                    </p>
                    <footer class="blockquote-footer"><%= gettext("Luke Strickland, Founder of Glimesh") %></footer>
                </blockquote>
            </div>
        </div>

        <p class="text-center mt-4">
            <img src="/images/logos/logo-for-navbar.png" alt="Glimesh">
        </p>

    </div>
</div>

lib/glimesh_web/templates/about/team.html.eex
<div class="jumbotron jumbotron-fluid jumbotron-glimesh d-flex align-items-center">
    <div class="container">
        <h1 class="display-4 text-center"><%= gettext("The Team") %></h1>
    </div>
</div>

<div class="card">
    <div class="card-body">
        <p class="m-0">
            <%= gettext("The Glimesh Team is a core group responsible for our company and the platform we provide our users. We're a diverse group of individuals working together for a common cause and trying to leave the industry better than we found it. We run Glimesh as an open company with an unusually flat organizational hierarchy.") %>
        </p>
    </div>
</div>

<div class="row mt-4 mb-4">
    <%= for user <- @users do %>
    <div class="col-md-3 mb-4">

        <div class="card text-center h-100">
            <h4 class="text-color-link mt-3 mb-3">
                <%= link user.displayname, to: Routes.user_profile_path(@conn, :index, user.username), class: "stretched-link text-color-link" %>
            </h4>
            <img src="<%= Glimesh.Avatar.url({user.avatar, user}, :original) %>"
                class="card-img-top img-avatar mx-auto mb-4" alt="<%= user.displayname %>">
            <div class="card-body <%= Glimesh.Accounts.Profile.user_role_color(user) %> rounded-bottom">
                <h5 class="card-title text-white mb-0"><%= user.team_role %></h5>
            </div>
        </div>
    </div>
    <% end %>
</div>


<div class="card">
    <div class="card-body">
        <h2 class="text-center"><%= gettext("Join Us!") %></h2>

        <p>
            <%= gettext("We also encourage our community to become part of our team as we know there are many talented people out there who wish to be part of something new. If you feel that you can offer Glimesh and the community your talents, whether that’s web development, designing, or moderation, then we would love to hear from you. If this is of any interest, please reach out to us in our Discord or head to") %><a href= "https://build.glimesh.tv"> <%= gettext("Building Glimesh") %></a> <%= gettext("to get involved.") %>
        </p>

        <div class="mt-4 mb-1 text-center">
            <a href="https://glimesh.tv/s/discord"
                class="btn btn-primary btn-lg mx-4"><%= gettext("Join our Discord") %></a>
        </div>

    </div>
</div>