lib/glimesh_web/router.ex
defmodule GlimeshWeb.Router do
  use GlimeshWeb, :router

  import GlimeshWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {GlimeshWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
    plug GlimeshWeb.Plugs.Floc
    plug GlimeshWeb.Plugs.Locale
    plug GlimeshWeb.Plugs.CfCountryPlug
    plug GlimeshWeb.Plugs.Ban
    plug GlimeshWeb.Plugs.UserAgent
    plug GlimeshWeb.UniqueUserPlug
    plug NavigationHistory.Tracker, excluded_paths: ["/users/log_in", "/users/register"]
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :graphql_alpha_api do
    plug :accepts, ["json"]
    # This route does not use session / cookies, so CORS can be wide open
    plug GlimeshWeb.Plugs.Cors
    plug :require_alpha_api_header
    plug GlimeshWeb.Plugs.ApiContextPlug
  end

  pipeline :graphql do
    plug :fetch_session
    plug :fetch_current_user
    plug :accepts, ["json"]
    plug GlimeshWeb.Plugs.OldApiContextPlug
  end

  pipeline :oauth do
    # This route does not use session / cookies, so CORS can be wide open
    plug GlimeshWeb.Plugs.Cors
    plug Plug.Parsers, parsers: [:urlendoded]
  end

  if Mix.env() in [:dev, :test] do
    scope "/" do
      pipe_through :browser

      forward "/sent_emails", Bamboo.SentEmailViewerPlug
    end
  end

  scope "/api/oauth", GlimeshWeb do
    pipe_through :oauth

    post "/token", OauthController, :token
    post "/revoke", OauthController, :revoke
    post "/introspect", OauthController, :introspect
  end

  scope "/api/webhook", GlimeshWeb do
    pipe_through :api

    # post "/stripe", WebhookController, :stripe
    post "/taxidpro", WebhookController, :taxidpro
  end

  scope "/api/graph" do
    pipe_through :graphql_alpha_api

    forward "/", Glimesh.Api.GraphiQLPlug,
      schema: Glimesh.Api.Schema,
      socket: GlimeshWeb.GraphApiSocket,
      default_url: {__MODULE__, :graph_default_url},
      socket_url: {__MODULE__, :graph_socket_url},
      interface: :playground,
      analyze_complexity: true,
      max_complexity: 500
  end

  scope "/api" do
    pipe_through :graphql

    forward "/", Absinthe.Plug.GraphiQL,
      schema: Glimesh.OldSchema,
      socket: GlimeshWeb.OldApiSocket,
      default_url: {__MODULE__, :graphiql_default_url},
      socket_url: {__MODULE__, :graphiql_socket_url}
  end

  ## Authentication routes
  scope "/", GlimeshWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    post "/users/log_in_tfa", UserSessionController, :tfa
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", GlimeshWeb do
    pipe_through [:browser, :require_authenticated_user]

    live "/platform_subscriptions", PlatformSubscriptionLive.Index, :index

    get "/users/social/twitter", UserSocialController, :twitter
    delete "/users/social/disconnect/:platform", UserSocialController, :disconnect

    get "/users/payments", UserPaymentsController, :index
    post "/users/payments/setup", UserPaymentsController, :setup
    get "/users/payments/taxes", UserPaymentsController, :taxes
    get "/users/payments/taxes_pending", UserPaymentsController, :taxes_pending
    get "/users/payments/connect", UserPaymentsController, :connect
    put "/users/payments/delete_default_payment", UserPaymentsController, :delete_default_payment

    get "/users/settings/profile", UserSettingsController, :profile
    get "/users/settings/stream", UserSettingsController, :stream

    get "/users/settings/channel_statistics", UserSettingsController, :channel_statistics
    get "/users/settings/addons", UserSettingsController, :addons
    get "/users/settings/emotes", UserSettingsController, :emotes
    get "/users/settings/upload_emotes", UserSettingsController, :upload_emotes
    get "/users/settings/hosting", UserSettingsController, :hosting

    put "/users/settings/create_channel", UserSettingsController, :create_channel
    put "/users/settings/delete_channel", UserSettingsController, :delete_channel
    get "/users/settings/preference", UserSettingsController, :preference
    put "/users/settings/preference", UserSettingsController, :update_preference
    put "/users/settings/update_profile", UserSettingsController, :update_profile
    put "/users/settings/update_channel", UserSettingsController, :update_channel
    get "/users/settings/notifications", UserSettingsController, :notifications

    get "/users/settings/security", UserSecurityController, :index
    put "/users/settings/update_password", UserSecurityController, :update_password
    put "/users/settings/update_email", UserSecurityController, :update_email
    get "/users/settings/confirm_email/:token", UserSecurityController, :confirm_email
    put "/users/settings/update_tfa", UserSecurityController, :update_tfa
    get "/users/settings/get_tfa", UserSecurityController, :get_tfa
    get "/users/settings/tfa_registered", UserSecurityController, :tfa_registered

    put "/users/settings/applications/:id/rotate", UserApplicationsController, :rotate
    resources "/users/settings/applications", UserApplicationsController

    resources "/users/settings/authorizations", UserAuthorizedAppsController,
      only: [:index, :delete],
      param: "id"

    get "/oauth/authorize", OauthController, :authorize
    post "/oauth/authorize", OauthController, :process_authorize
  end

  scope "/", GlimeshWeb do
    pipe_through [:browser, :require_authenticated_user, :require_user_has_channel]

    post "/users/settings/channel/mods/ban_user",
         ChannelModeratorController,
         :ban_user

    delete "/users/settings/channel/mods/unban_user/:username",
           ChannelModeratorController,
           :unban_user

    resources "/users/settings/channel/mods", ChannelModeratorController
  end

  scope "/admin", GlimeshWeb do
    pipe_through [:browser, :require_admin_user]

    import Phoenix.LiveDashboard.Router

    live_dashboard "/phoenix/dashboard", metrics: GlimeshWeb.Telemetry, ecto_repos: [Glimesh.Repo]

    live "/categories", Admin.CategoryLive.Index, :index
    live "/categories/new", Admin.CategoryLive.Index, :new
    live "/categories/:id/edit", Admin.CategoryLive.Index, :edit

    live "/categories/:id", Admin.CategoryLive.Show, :show
    live "/categories/:id/show/edit", Admin.CategoryLive.Show, :edit

    live "/tags", Admin.TagLive.Index, :index
    live "/tags/new", Admin.TagLive.Index, :new
    live "/tags/:id/edit", Admin.TagLive.Index, :edit
  end

  scope "/gct", GlimeshWeb do
    pipe_through [:browser, :require_gct_user]

    get "/", GctController, :index
    get "/me", GctController, :edit_self
    get "/unauthorized", GctController, :unauthorized

    # Lookup scopes
    get "/lookup/user", GctController, :username_lookup
    get "/lookup/channel", GctController, :channel_lookup
    get "/lookup/channel/:channel_id/chat", GctController, :channel_chat_log
    get "/lookup/user/:user_id/chat", GctController, :user_chat_log

    # Editing profile scopes
    get "/edit/profile/:username", GctController, :edit_user_profile
    put "/edit/profile/:username/update", GctController, :update_user_profile

    # Editing user scopes
    get "/edit/:username", GctController, :edit_user
    put "/edit/:username/update", GctController, :update_user

    # Editing channel scopes
    get "/edit/channel/:channel_id", GctController, :edit_channel
    post "/edit/channel/:channel_id/shutdown", GctController, :shutdown_channel
    put "/edit/channel/:channel_id/update", GctController, :update_channel
    put "/edit/channel/:channel_id/delete", GctController, :delete_channel

    # Audit log
    get "/audit-log", GctController, :audit_log

    # Emote scopes
    get "/global-emotes", GctController, :global_emotes
    get "/review-emotes", GctController, :review_emotes

    # Categories and subcategories and tags and probably more
  end

  scope "/", GlimeshWeb do
    pipe_through [:browser, :require_events_team_user]

    live "/eventsteam", EventsTeam.EventsAdminLive, :index
  end

  scope "/", GlimeshWeb do
    pipe_through [:browser]

    get "/about", AboutController, :index
    get "/about/streaming", AboutController, :streaming
    get "/about/team", AboutController, :team
    get "/about/mission", AboutController, :mission
    get "/about/alpha", AboutController, :alpha
    get "/about/faq", AboutController, :faq
    get "/about/privacy", AboutController, :privacy
    get "/about/terms", AboutController, :terms
    get "/about/conduct", AboutController, :conduct
    get "/about/credits", AboutController, :credits
    get "/about/dmca", AboutController, :dmca

    live "/about/open-data", About.OpenDataLive, :index
    live "/about/open-data/subscriptions", About.OpenDataLive, :subscriptions
    live "/about/open-data/streams", About.OpenDataLive, :streams

    get "/events", EventsTeamController, :events_team

    get "/blog", BlogMigrationController, :redirect_blog
    get "/blog/:slug", BlogMigrationController, :redirect_post

    live "/", HomepageLive, :index
    live "/streams", StreamsLive.Index, :index
    live "/streams/following", StreamsLive.Following, :index
    live "/streams/:category", StreamsLive.List, :index

    live "/users", UserLive.Index, :index

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new

lib/glimesh_web/views/layout_view.ex
defmodule GlimeshWeb.LayoutView do
  use GlimeshWeb, :view

  def html_root_tags(conn) do
    []
    |> site_theme_attribute(conn)
    |> lang_attribute(conn)
    |> Enum.join(" ")
  end

  defp site_theme_attribute(attributes, conn) do
    theme = site_theme(conn)
    ["data-theme=\"#{theme}\"" | attributes]
  end

  defp lang_attribute(attributes, conn) do
    locale = site_locale(conn)
    ["lang=\"#{locale}\"" | attributes]
  end

  def site_theme_label(conn) do
    case site_theme(conn) do
      "dark" -> "🌘"
      "light" -> "☀️"
    end
  end

  def site_locale_label(conn) do
    site_locale(conn)
  end

  def site_locale(conn) do
    case Plug.Conn.get_session(conn, :locale) do
      nil ->
        "en"

      locale ->
        locale
    end
  end

  def site_theme(conn) do
    case Plug.Conn.get_session(conn, :site_theme) do
      nil ->
        "dark"

      theme ->
        theme
    end
  end

  # About Paths
  def active_about_path(conn, action) do
    truthy_active(controller_action(conn) == [GlimeshWeb.AboutController, action])
  end

  # User Settings Paths

  def active_user_profile_path(conn) do
    truthy_active(controller_action(conn) == [GlimeshWeb.UserSettingsController, :profile])
  end

  def active_user_stream_path(conn) do
    truthy_active(controller_action(conn) == [GlimeshWeb.UserSettingsController, :stream])
  end

  def active_user_emotes_path(conn) do
    truthy_active(
      controller_action(conn) == [GlimeshWeb.UserSettingsController, :emotes] or
        controller_action(conn) == [GlimeshWeb.UserSettingsController, :upload_emotes]
    )
  end

  def active_user_hosting_path(conn) do
    truthy_active(controller_action(conn) == [GlimeshWeb.UserSettingsController, :hosting])
  end

  def active_channel_addons_path(conn) do
    truthy_active(controller_action(conn) == [GlimeshWeb.UserSettingsController, :addons])
  end

  def active_user_payments_path(conn) do
    truthy_active(controller_action(conn) == [GlimeshWeb.UserPaymentsController, :index])
  end

  def active_user_settings_path(conn) do
    truthy_active(controller_action(conn) == [GlimeshWeb.UserSettingsController, :preference])
  end

  def active_user_notifications_path(conn) do
    truthy_active(controller_action(conn) == [GlimeshWeb.UserSettingsController, :notifications])
  end

  def active_channel_statistics_path(conn) do
    truthy_active(
      controller_action(conn) == [GlimeshWeb.UserSettingsController, :channel_statistics]
    )
  end

  def active_user_security_path(conn) do
    truthy_active(controller_action(conn) == [GlimeshWeb.UserSecurityController, :index])
  end

  def active_user_applications_path(conn) do
    truthy_active(hd(controller_action(conn)) == GlimeshWeb.UserApplicationsController)
  end

  def active_user_authorizations_path(conn) do
    truthy_active(
      hd(controller_action(conn)) == GlimeshWeb.Oauth2Provider.AuthorizedApplicationController
    )
  end

  def active_channel_moderator_path(conn) do
    truthy_active(hd(controller_action(conn)) == GlimeshWeb.ChannelModeratorController)
  end

  # GCT Path checks
  def active_gct_dashboard_path(conn) do
    truthy_active(controller_action(conn) == [GlimeshWeb.GctController, :index])
  end

  def active_gct_audit_log_path(conn) do
    truthy_active(controller_action(conn) == [GlimeshWeb.GctController, :audit_log])
  end

  def active_gct_global_emotes_path(conn) do
    truthy_active(controller_action(conn) == [GlimeshWeb.GctController, :global_emotes])
  end

  def active_gct_review_emotes_path(conn) do
    truthy_active(controller_action(conn) == [GlimeshWeb.GctController, :review_emotes])
  end

  defp controller_action(conn) do
    [controller_module(conn), action_name(conn)]
  end

  defp truthy_active(stmt) do
    if stmt do
      "active"
    else
      ""
    end
  end

  def count_live_following_channels(%{assigns: %{current_user: user}}) do
    count = length(Glimesh.ChannelLookups.list_live_followed_channels(user))

    if count > 0 do
      count
    else
      nil
    end
  end

  def count_live_following_channels(_) do
    nil
  end

  def count_live_hosted_channels(%{assigns: %{current_user: user}}) do
    count = Glimesh.ChannelLookups.count_live_followed_channels_that_are_hosting(user)

    if count > 0 do
      count
    else
      nil
    end
  end

  def count_live_hosted_channels(_) do
    nil
  end
end

lib/glimesh_web/templates/layout/about.html.eex
<div class="container">
    <div class="row justify-content-md-center">
        <div class="col-md-12">

            <h1 class="text-center mt-4 mb-4"><%= gettext("About Us") %></h1>

            <ul class="nav nav-fill nav-pagenav m-4">
                <li class="nav-item <%= active_about_path(@conn, :index) %>">
                    <%= link gettext("About Glimesh"), to: Routes.about_path(@conn, :index), class: "nav-link" %>
                </li>
                <li class="nav-item <%= active_about_path(@conn, :alpha) %>">
                    <%= link gettext("Alpha"), to: Routes.about_path(@conn, :alpha), class: "nav-link" %>
                </li>
                <li class="nav-item <%= active_about_path(@conn, :streaming) %>">
                    <%= link gettext("Streaming"), to: Routes.about_path(@conn, :streaming), class: "nav-link" %>
                </li>
                <li class="nav-item <%= active_about_path(@conn, :team) %>">
                    <%= link gettext("The Team"), to: Routes.about_path(@conn, :team), class: "nav-link" %>
                </li>
                <li class="nav-item <%= active_about_path(@conn, :mission) %>">
                    <%= link gettext("Our Mission"), to: Routes.about_path(@conn, :mission), class: "nav-link" %>
                </li>
            </ul>

            <%= @inner_content %>

        </div>
    </div>
</div>

lib/glimesh_web/templates/layout/app.html.eex
<!-- app.html.eex -->
<%= if get_flash(@conn, :info) do %>
<p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
<% end %>
<%= if get_flash(@conn, :error) do %>
<p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
<% end %>
<!-- end app.html.eex -->
<%= @inner_content %>

lib/glimesh_web/templates/layout/email.text.eex
<%= @inner_content %>

==================================

Glimesh, Inc.
<%= Application.get_env(:glimesh, :email_physical_address) %>
United States of America

==================================

lib/glimesh_web/templates/layout/gct-sidebar.html.eex
<div class="sidebar">
    <%= link class: "list-group-item list-group-item-action " <> active_gct_dashboard_path(@conn), to: Routes.gct_path(@conn, :index) do %>
    <i class="fas fa-tools fa-fw"></i> <%= gettext("Dashboard") %>
    <% end %>
    <%= if Bodyguard.permit?(Glimesh.CommunityTeam, :view_audit_log, @current_user) do %>
    <%= link class: "list-group-item list-group-item-action " <> active_gct_audit_log_path(@conn), to: Routes.gct_path(@conn, :audit_log) do %>
    <i class="fas fa-clipboard-list fa-fw"></i> <%= gettext("Audit Log") %>
    <% end %>
    <% end %>
    <%= if Bodyguard.permit?(Glimesh.CommunityTeam, :upload_global_emotes, @current_user) do %>
    <%= link class: "list-group-item list-group-item-action " <> active_gct_global_emotes_path(@conn), to: Routes.gct_path(@conn, :global_emotes) do %>
    <i class="fas fa-smile fa-fw"></i> <%= gettext("Global Emotes") %>
    <% end %>
    <% end %>
    <%= if Bodyguard.permit?(Glimesh.CommunityTeam, :manage_emotes, @current_user) do %>
    <%= link class: "list-group-item list-group-item-action " <> active_gct_review_emotes_path(@conn), to: Routes.gct_path(@conn, :review_emotes) do %>
    <i class="fas fa-smile fa-fw"></i> <%= gettext("Review Emotes") %>
    <% end %>
    <% end %>
</div>
<div class="content">
    <%= if get_flash(@conn, :info) do %>
    <p class="alert alert-info mx-4 mt-1" role="alert"><%= get_flash(@conn, :info) %></p>
    <% end %>
    <%= if get_flash(@conn, :error) do %>
    <p class="alert alert-danger mx-4 mt-1" role="alert"><%= get_flash(@conn, :error) %></p>
    <% end %>

    <%= @inner_content %>
</div>

lib/glimesh_web/templates/layout/text.html.eex
<div class="container mt-4">
    <div class="row justify-content-md-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-body text-heavy-content">

                    <%= @inner_content %>

                </div>
            </div>
        </div>
    </div>
</div>

lib/glimesh_web/templates/layout/user-sidebar.html.eex
<div class="container-fluid">
    <div class="row mt-3">
        <div class="col-lg-2 user-sidebar">
            <div class="list-group list-group-flush">
                <%= link class: "list-group-item list-group-item-action " <> active_user_profile_path(@conn), to: Routes.user_settings_path(@conn, :profile) do %>
                <i class="fas fa-user fa-fw"></i> <%= gettext("Profile") %>
                <% end %>
                <%= link class: "list-group-item list-group-item-action " <> active_user_payments_path(@conn), to: Routes.user_payments_path(@conn, :index) do %>
                <i class="fas fa-money-bill fa-fw"></i> <%= gettext("Payments") %>
                <% end %>
                <%= link class: "list-group-item list-group-item-action " <> active_user_settings_path(@conn), to: Routes.user_settings_path(@conn, :preference) do %>
                <i class="fas fa-cog fa-fw"></i> <%= gettext("Preferences") %>
                <% end %>
                <%= link class: "list-group-item list-group-item-action " <> active_user_notifications_path(@conn), to: Routes.user_settings_path(@conn, :notifications) do %>
                <i class="fas fa-envelope fa-fw"></i> <%= gettext("Notifications") %>
                <% end %>
                <%= link class: "list-group-item list-group-item-action " <> active_user_security_path(@conn), to: Routes.user_security_path(@conn, :index) do %>
                <i class="fas fa-lock fa-fw"></i> <%= gettext("Security") %>
                <% end %>
                <%= link class: "list-group-item list-group-item-action " <> active_user_authorizations_path(@conn), to: Routes.user_authorized_apps_path(@conn, :index) do %>
                <i class="fas fa-robot fa-fw"></i> <%= gettext("Authorizations") %>
                <% end %>
            </div>

            <hr>
            <h4 class="text-center"><%= gettext("Channel") %></h4>
            <div class="list-group list-group-flush">
                <%= if Glimesh.ChannelLookups.get_channel_for_user(@current_user) do %>
                <%= link class: "list-group-item list-group-item-action " <> active_user_stream_path(@conn), to: Routes.user_settings_path(@conn, :stream) do %>
                <i class="fas fa-video fa-fw"></i> <%= gettext("Channel Settings") %>
                <% end %>
                <%= link class: "list-group-item list-group-item-action " <> active_channel_addons_path(@conn), to: Routes.user_settings_path(@conn, :addons) do %>
                <i class="fas fa-hand-holding-usd fa-fw"></i> <%= gettext("Support Modal") %>
                <% end %>
                <%= link class: "list-group-item list-group-item-action " <> active_channel_statistics_path(@conn), to: Routes.user_settings_path(@conn, :channel_statistics) do %>
                <i class="fas fa-chart-bar fa-fw"></i> <%= gettext("Statistics") %>
                <% end %>
                <%= link class: "list-group-item list-group-item-action " <> active_channel_moderator_path(@conn), to: Routes.channel_moderator_path(@conn, :index) do %>
                <i class="fas fa-hammer fa-fw"></i> <%= gettext("Moderators") %>
                <% end %>
                <%= link class: "list-group-item list-group-item-action " <> active_user_emotes_path(@conn), to: Routes.user_settings_path(@conn, :emotes) do %>
                <i class="fas fa-smile fa-fw"></i> <%= gettext("Emotes") %>
                <% end %>
                <%= link class: "list-group-item list-group-item-action " <> active_user_hosting_path(@conn), to: Routes.user_settings_path(@conn, :hosting) do %>
                <i class="fas fa-tv fa-fw"></i> <%= gettext("Hosting") %>
                <% end %>
                <% else %>
                <%= link class: "list-group-item list-group-item-action " <> active_user_stream_path(@conn), to: Routes.user_settings_path(@conn, :stream) do %>
                <i class="fas fa-video fa-fw"></i> <%= gettext("Create Channel") %>
                <% end %>
                <% end %>
            </div>

            <hr>
            <h4 class="text-center">Developers</h4>
            <div class="list-group list-group-flush">
                <%= link class: "list-group-item list-group-item-action " <> active_user_applications_path(@conn), to: Routes.user_applications_path(@conn, :index) do %>
                <i class="fas fa-code fa-fw"></i> <%= gettext("Applications") %>
                <% end %>
            </div>
        </div>
        <div class="col-lg-10">

            <!-- user-sidebar.html.eex -->
            <%# BUG this section needs to be removed, it conflicts with app.html.eex and the few settings pages that rely on this need to be fixed %>
            <%= if get_flash(@conn, :info) do %>
            <p class="alert alert-info mt-4" role="alert"><%= get_flash(@conn, :info) %></p>
            <% end %>
            <%= if get_flash(@conn, :error) do %>
            <p class="alert alert-danger mt-4" role="alert"><%= get_flash(@conn, :error) %></p>
            <% end %>

            <!-- user-sidebar.html.eex -->
            <%= @inner_content %>

        </div>
    </div>
</div>