lib/glimesh_web/router.ex
    plug Plug.Parsers, parsers: [:urlendoded]
  end

  if Mix.env() in [:dev, :test] do
    scope "/" do
      pipe_through :browser

      forward "/sent_emails", Bamboo.SentEmailViewerPlug
    end
  end

  scope "/api/oauth", GlimeshWeb do
    pipe_through :oauth

    post "/token", OauthController, :token
    post "/revoke", OauthController, :revoke
    post "/introspect", OauthController, :introspect
  end

  scope "/api/webhook", GlimeshWeb do
    pipe_through :api

    # post "/stripe", WebhookController, :stripe
    post "/taxidpro", WebhookController, :taxidpro
  end

  scope "/api/graph" do
    pipe_through :graphql_alpha_api

    forward "/", Glimesh.Api.GraphiQLPlug,
      schema: Glimesh.Api.Schema,
      socket: GlimeshWeb.GraphApiSocket,
      default_url: {__MODULE__, :graph_default_url},
      socket_url: {__MODULE__, :graph_socket_url},
      interface: :playground,
      analyze_complexity: true,
      max_complexity: 500
  end

  scope "/api" do
    pipe_through :graphql

    forward "/", Absinthe.Plug.GraphiQL,
      schema: Glimesh.OldSchema,
      socket: GlimeshWeb.OldApiSocket,
      default_url: {__MODULE__, :graphiql_default_url},
      socket_url: {__MODULE__, :graphiql_socket_url}
  end

  ## Authentication routes
  scope "/", GlimeshWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    post "/users/log_in_tfa", UserSessionController, :tfa
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", GlimeshWeb do
    pipe_through [:browser, :require_authenticated_user]

    live "/platform_subscriptions", PlatformSubscriptionLive.Index, :index

    get "/users/social/twitter", UserSocialController, :twitter
    delete "/users/social/disconnect/:platform", UserSocialController, :disconnect

    get "/users/payments", UserPaymentsController, :index
    post "/users/payments/setup", UserPaymentsController, :setup
    get "/users/payments/taxes", UserPaymentsController, :taxes
    get "/users/payments/taxes_pending", UserPaymentsController, :taxes_pending
    get "/users/payments/connect", UserPaymentsController, :connect
    put "/users/payments/delete_default_payment", UserPaymentsController, :delete_default_payment

    get "/users/settings/profile", UserSettingsController, :profile
    get "/users/settings/stream", UserSettingsController, :stream

    get "/users/settings/channel_statistics", UserSettingsController, :channel_statistics
    get "/users/settings/addons", UserSettingsController, :addons
    get "/users/settings/emotes", UserSettingsController, :emotes
    get "/users/settings/upload_emotes", UserSettingsController, :upload_emotes
    get "/users/settings/hosting", UserSettingsController, :hosting

    put "/users/settings/create_channel", UserSettingsController, :create_channel
    put "/users/settings/delete_channel", UserSettingsController, :delete_channel
    get "/users/settings/preference", UserSettingsController, :preference
    put "/users/settings/preference", UserSettingsController, :update_preference
    put "/users/settings/update_profile", UserSettingsController, :update_profile
    put "/users/settings/update_channel", UserSettingsController, :update_channel
    get "/users/settings/notifications", UserSettingsController, :notifications

    get "/users/settings/security", UserSecurityController, :index
    put "/users/settings/update_password", UserSecurityController, :update_password
    put "/users/settings/update_email", UserSecurityController, :update_email
    get "/users/settings/confirm_email/:token", UserSecurityController, :confirm_email
    put "/users/settings/update_tfa", UserSecurityController, :update_tfa
    get "/users/settings/get_tfa", UserSecurityController, :get_tfa
    get "/users/settings/tfa_registered", UserSecurityController, :tfa_registered

    put "/users/settings/applications/:id/rotate", UserApplicationsController, :rotate
    resources "/users/settings/applications", UserApplicationsController

    resources "/users/settings/authorizations", UserAuthorizedAppsController,
      only: [:index, :delete],
      param: "id"

    get "/oauth/authorize", OauthController, :authorize
    post "/oauth/authorize", OauthController, :process_authorize
  end

  scope "/", GlimeshWeb do
    pipe_through [:browser, :require_authenticated_user, :require_user_has_channel]

    post "/users/settings/channel/mods/ban_user",
         ChannelModeratorController,
         :ban_user

    delete "/users/settings/channel/mods/unban_user/:username",
           ChannelModeratorController,
           :unban_user

    resources "/users/settings/channel/mods", ChannelModeratorController
  end

  scope "/admin", GlimeshWeb do
    pipe_through [:browser, :require_admin_user]

    import Phoenix.LiveDashboard.Router

    live_dashboard "/phoenix/dashboard", metrics: GlimeshWeb.Telemetry, ecto_repos: [Glimesh.Repo]

    live "/categories", Admin.CategoryLive.Index, :index
    live "/categories/new", Admin.CategoryLive.Index, :new
    live "/categories/:id/edit", Admin.CategoryLive.Index, :edit

    live "/categories/:id", Admin.CategoryLive.Show, :show
    live "/categories/:id/show/edit", Admin.CategoryLive.Show, :edit

    live "/tags", Admin.TagLive.Index, :index
    live "/tags/new", Admin.TagLive.Index, :new
    live "/tags/:id/edit", Admin.TagLive.Index, :edit
  end

  scope "/gct", GlimeshWeb do
    pipe_through [:browser, :require_gct_user]

    get "/", GctController, :index
    get "/me", GctController, :edit_self
    get "/unauthorized", GctController, :unauthorized

    # Lookup scopes
    get "/lookup/user", GctController, :username_lookup
    get "/lookup/channel", GctController, :channel_lookup
    get "/lookup/channel/:channel_id/chat", GctController, :channel_chat_log
    get "/lookup/user/:user_id/chat", GctController, :user_chat_log

    # Editing profile scopes
    get "/edit/profile/:username", GctController, :edit_user_profile
    put "/edit/profile/:username/update", GctController, :update_user_profile

    # Editing user scopes
    get "/edit/:username", GctController, :edit_user
    put "/edit/:username/update", GctController, :update_user

    # Editing channel scopes
    get "/edit/channel/:channel_id", GctController, :edit_channel
    post "/edit/channel/:channel_id/shutdown", GctController, :shutdown_channel
    put "/edit/channel/:channel_id/update", GctController, :update_channel
    put "/edit/channel/:channel_id/delete", GctController, :delete_channel

    # Audit log
    get "/audit-log", GctController, :audit_log

    # Emote scopes
    get "/global-emotes", GctController, :global_emotes
    get "/review-emotes", GctController, :review_emotes

    # Categories and subcategories and tags and probably more
  end

  scope "/", GlimeshWeb do
    pipe_through [:browser, :require_events_team_user]

    live "/eventsteam", EventsTeam.EventsAdminLive, :index
  end

  scope "/", GlimeshWeb do
    pipe_through [:browser]

    get "/about", AboutController, :index
    get "/about/streaming", AboutController, :streaming
    get "/about/team", AboutController, :team
    get "/about/mission", AboutController, :mission
    get "/about/alpha", AboutController, :alpha
    get "/about/faq", AboutController, :faq
    get "/about/privacy", AboutController, :privacy
    get "/about/terms", AboutController, :terms
    get "/about/conduct", AboutController, :conduct
    get "/about/credits", AboutController, :credits
    get "/about/dmca", AboutController, :dmca

    live "/about/open-data", About.OpenDataLive, :index
    live "/about/open-data/subscriptions", About.OpenDataLive, :subscriptions
    live "/about/open-data/streams", About.OpenDataLive, :streams

    get "/events", EventsTeamController, :events_team

    get "/blog", BlogMigrationController, :redirect_blog
    get "/blog/:slug", BlogMigrationController, :redirect_post

    live "/", HomepageLive, :index
    live "/streams", StreamsLive.Index, :index
    live "/streams/following", StreamsLive.Following, :index
    live "/streams/:category", StreamsLive.List, :index

    live "/users", UserLive.Index, :index

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :confirm

    post "/quick_preferences", QuickPreferenceController, :update_preference

    # Short Links
    get "/s/event-form", ShortLinkController, :event_form
    get "/s/discord", ShortLinkController, :community_discord

    # This must be the last route
    live "/:username", UserLive.Stream, :index
    live "/:username/support", UserLive.Stream, :support
    live "/:username/support/:tab", UserLive.Stream, :support
    live "/:username/profile", UserLive.Profile, :index
    live "/:username/profile/followers", UserLive.Followers, :followers
    live "/:username/profile/following", UserLive.Followers, :following
    live "/:username/chat", ChatLive.PopOut, :index
  end

  alias GlimeshWeb.Router.Helpers, as: Routes

  def graphiql_default_url(conn) do
    Routes.url(conn) <> "/api"
  end

  def graphiql_socket_url(conn) do
    (Routes.url(conn) <> "/api/socket")
    |> String.replace("http", "ws")
    |> String.replace("https", "wss")
  end

  def graph_default_url(conn) do
    Routes.url(conn) <> "/api/graph"
  end

  def graph_socket_url(conn) do
    (Routes.url(conn) <> "/api/graph/socket")
    |> String.replace("http", "ws")

lib/glimesh_web/controllers/user_applications_controller.ex
defmodule GlimeshWeb.UserApplicationsController do
  use GlimeshWeb, :controller

  alias Glimesh.Apps
  alias Glimesh.Apps.App

  action_fallback GlimeshWeb.FallbackController

  plug :put_layout, "user-sidebar.html"

  plug :assign_user

  def index(conn, _params) do
    applications = Apps.list_apps(conn.assigns.user)

    render(conn, "index.html",
      page_title: format_page_title(gettext("Applications")),
      applications: applications
    )
  end

  def show(conn, %{"id" => id}) do
    applications = Apps.list_apps(conn.assigns.user)

    with {:ok, application} <- Apps.get_app(conn.assigns.user, id) do
      render(conn, "show.html",
        page_title: format_page_title(application.name),
        application: application,
        applications: applications
      )
    end
  end

  def new(conn, _params) do
    changeset = Apps.change_app(%App{})

    render(conn, "new.html",
      page_title: format_page_title(gettext("Create Application")),
      changeset: changeset
    )
  end

  def create(conn, %{"app" => application_params}) do
    user = conn.assigns.current_user

    case Apps.create_app(user, application_params) do
      {:ok, application} ->
        conn
        |> put_flash(:info, gettext("Application created successfully."))
        |> redirect(to: Routes.user_applications_path(conn, :show, application.id))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def edit(conn, %{"id" => id}) do
    with {:ok, app} <- Apps.get_app(conn.assigns.user, id) do
      changeset = Apps.change_app(app)

      render(conn, "edit.html",
        page_title: format_page_title(gettext("Update Application")),
        application: app,
        changeset: changeset
      )
    end
  end

  def update(conn, %{"id" => id, "app" => application_params}) do
    user = conn.assigns.user

    with {:ok, app} <- Apps.get_app(user, id) do
      case Apps.update_app(user, app, application_params) do
        {:ok, app} ->
          conn
          |> put_flash(:info, gettext("Application updated successfully."))
          |> redirect(to: Routes.user_applications_path(conn, :show, app))

        {:error, %Ecto.Changeset{} = changeset} ->
          render(conn, "edit.html", application: app, changeset: changeset)

        {:error, :unauthorized} ->
          conn
          |> put_flash(:error, gettext("You do not have permission to update this app."))
          |> redirect(to: Routes.user_applications_path(conn, :edit, app))
      end
    end
  end

  def rotate(conn, %{"id" => id}) do
    user = conn.assigns.user

    with {:ok, app} <- Apps.get_app(user, id) do
      case Apps.rotate_oauth_app(user, app) do
        {:ok, _oauth_app} ->
          conn
          |> put_flash(:info, gettext("OAuth Client ID & Client Secret rotated successfully."))
          |> redirect(to: Routes.user_applications_path(conn, :show, app))

        {:error, :unauthorized} ->
          conn
          |> put_flash(:error, gettext("You do not have permission to rotate this apps keys."))
          |> redirect(to: Routes.user_applications_path(conn, :show, app))
      end
    end
  end

  defp assign_user(conn, _opts) do
    user = conn.assigns.current_user

    conn |> assign(:user, user)
  end
end

lib/glimesh_web/views/user_applications_view.ex
defmodule GlimeshWeb.UserApplicationsView do
  use GlimeshWeb, :view
end

lib/glimesh_web/templates/user_applications/edit.html.eex
<div class="container mt-4">
  <h1><%= gettext("Edit Application") %></h1>

  <div class="card">
    <div class="card-body">
      <%= render "form.html", Map.put(assigns, :action, Routes.user_applications_path(@conn, :update, @changeset.data)) %>
    </div>
  </div>
</div>

lib/glimesh_web/templates/user_applications/form.html.eex
<%= form_for @changeset, @action, [multipart: true, class: "form"], fn f -> %>
<%= if @changeset.action do %>
<div class="alert alert-danger">
    <p><%= gettext("Oops, something went wrong! Please check the errors below.") %></p>
</div>
<% end %>

<div class="form-group">
    <%= label f, gettext("Name") %>
    <%= text_input f, :name, class: "form-control" %>
    <%= error_tag f, :name %>
</div>

<div class="form-group">
    <%= label f, gettext("Homepage") %>
    <%= text_input f, :homepage_url, class: "form-control" %>
    <%= error_tag f, :homepage_url %>
</div>

<div class="form-group">
    <%= label f, gettext("Description") %>
    <%= text_input f, :description, class: "form-control" %>
    <%= error_tag f, :description %>
</div>

<div class="form-group">
    <%= label f, gettext("Image") %>
    <div class="custom-file">
        <%= file_input f, :logo, id: "customFile", class: "custom-file-input custom-file form-control", accept: "image/png, image/jpeg" %>
        <label class="custom-file-label" for="customFile" data-browse="<%= gettext("Browse for Images") %>"><%= gettext("Choose file") %></label>
    </div>
    <%= error_tag f, :logo %>
</div>

<%= inputs_for f, :client, fn oa -> %>
<div class="form-group">
    <%= label oa, gettext("Allowed Redirect URI's") %>
    <%= textarea oa, :redirect_uris, class: "form-control" %>
    <%= error_tag oa, :redirect_uris %>
    <span class="help-block"><%= gettext("Use one line per URI") %></span>
</div>
<% end %>


<div class="form-group">
    <%= submit gettext("Save Application"), class: "btn btn-primary" %>
</div>
<% end %>

lib/glimesh_web/templates/user_applications/index.html.eex
<div class="container mt-4">
  <div class="row">
    <div class="col-9">
      <h2><%= gettext("Applications") %></h2>
    </div>
    <div class="col-3">
      <%= link gettext("Create Application"), class: "btn btn-primary btn-block", to: Routes.user_applications_path(@conn, :new) %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-3">
      <div class="list-group">
        <%= for app <- @applications do %>
        <%= link app.name, class: "list-group-item list-group-item-action", to: Routes.user_applications_path(@conn, :show, app) %>
        <% end %>
      </div>
    </div>
    <div class="col-md-9">

      <div class="card">
        <div class="card-body">
          <p>
            <%= gettext("Want to build a chat bot, an online tool, or other service that integrates with Glimesh? You're in the right place! Create an Application to get started and check out our API documentation if you need some guidance.") %>
          </p>
          <p>
            <%= link gettext("API Documentation"), to: "https://glimesh.github.io/api-docs/", class: "btn btn-sm btn-info", target: "_blank" %>
          </p>
        </div>
      </div>
    </div>
  </div>

</div>

lib/glimesh_web/templates/user_applications/new.html.eex
<div class="container mt-4">
  <div class="row">
    <div class="col-10">
      <h2><%= gettext("Create Application") %></h2>
    </div>
    <div class="col-2">
      <%= link gettext("Back"), class: "btn btn-primary btn-block", to: Routes.user_applications_path(@conn, :index) %>
    </div>
  </div>

  <div class="card">
    <div class="card-body">
      <%= render "form.html", Map.put(assigns, :action, Routes.user_applications_path(@conn, :create)) %>
    </div>
  </div>
</div>

lib/glimesh_web/templates/user_applications/show.html.eex
<div class="container mt-4">
    <div class="row">
        <div class="col-9">
            <h2><%= gettext("Applications") %></h2>
        </div>
        <div class="col-3">
            <%= link gettext("Create Application"), class: "btn btn-primary btn-block", to: Routes.user_applications_path(@conn, :new) %>
        </div>
    </div>

    <div class="row">
        <div class="col-md-3">
            <div class="list-group">
                <%= for app <- @applications do %>
                <%= link app.name, class: "list-group-item list-group-item-action", to: Routes.user_applications_path(@conn, :show, app) %>
                <% end %>
            </div>
        </div>
        <div class="col-md-9">

            <div class="card">
                <div class="card-body">
                    <div class="media">
                        <img class="mr-3" src="<%= Glimesh.AppLogo.url({@application.logo, @application}, :original) %>" alt="Generic placeholder image">
                        <div class="media-body">
                            <h5 class="mt-0"><%= @application.name %></h5>
                            <p><%= @application.description %></p>
                            <p><i class="fas fa-wifi fa-w"></i> <%= @application.homepage_url %></p>
                        </div>
                    </div>

                    <h3><%= gettext("Credentials") %></h3>
                    <div class="form-group">
                        <label for="clientId"><%= gettext("Client ID") %></label>
                        <div class="input-group">
                            <input id="clientId" type="text" class="form-control" readonly value="<%= Glimesh.Apps.get_client_id(@application) %>">
                            <div class="input-group-append">
                                <%= live_render(@conn, GlimeshWeb.Components.ClickToCopy, id: "oauth_application_uid", session: %{"value" => Glimesh.Apps.get_client_id(@application)}) %>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="secretKey"><%= gettext("Secret Key") %></label>
                        <div class="input-group">
                            <input id="secretKey" type="text" class="form-control" readonly value="<%= Glimesh.Apps.get_client_secret(@application) %>">
                            <div class="input-group-append">
                                <%= live_render(@conn, GlimeshWeb.Components.ClickToCopy, id: "oauth_application_secret", session: %{"value" => Glimesh.Apps.get_client_secret(@application)}) %>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="tokenRoute"><%= gettext("OAuth Token URL") %></label>
                        <div class="input-group">
                            <input id="tokenRoute" type="text" class="form-control" readonly value="<%= Routes.oauth_url(@conn, :token) %>">
                            <div class="input-group-append">
                                <%= live_render(@conn, GlimeshWeb.Components.ClickToCopy, id: "oauth_application_token_url", session: %{"value" => Routes.oauth_url(@conn, :token)}) %>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="authorizationRoute"><%= gettext("OAuth Authorization URL") %></label>
                        <div class="input-group">
                            <input id="authorizationRoute" type="text" class="form-control" readonly value="<%= Routes.oauth_url(@conn, :authorize) %>">
                            <div class="input-group-append">
                                <%= live_render(@conn, GlimeshWeb.Components.ClickToCopy, id: "oauth_application_authorization_url", session: %{"value" => Routes.oauth_url(@conn, :authorize)}) %>
                            </div>
                        </div>
                    </div>


                    <h3><%= gettext("Callbacks") %></h3>
                    <table class="table">
                        <tbody>
                            <%= for redirect_uri <- Glimesh.Apps.get_client_redirect_uris(@application) do %>
                            <tr>
                                <td>
                                    <code><%= redirect_uri %></code>
                                </td>
                                <td>
                                    <%= link gettext("Authorize"), to: Routes.oauth_path(@conn, :authorize, client_id: Glimesh.Apps.get_client_id(@application), redirect_uri: redirect_uri, response_type: "code"), target: "_blank" %>
                                </td>
                            </tr>
                            <% end %>
                        </tbody>
                    </table>
                </div>
                <div class="card-footer">
                    <%= link gettext("Edit Application"), class: "btn btn-primary", to: Routes.user_applications_path(@conn, :edit, @application) %>
                    &nbsp;
                    <%= button gettext("Rotate Keys"), class: "btn btn-danger", method: :put, to: Routes.user_applications_path(@conn, :rotate, @application), "data-confirm": "Are you sure you want to rotate the Client ID and Secret Key? This will require updating your applications as well." %>
                </div>
            </div>
        </div>
    </div>

</div>