lib/glimesh_web/router.ex
defmodule GlimeshWeb.Router do
  use GlimeshWeb, :router

  import GlimeshWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {GlimeshWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
    plug GlimeshWeb.Plugs.Floc
    plug GlimeshWeb.Plugs.Locale
    plug GlimeshWeb.Plugs.CfCountryPlug
    plug GlimeshWeb.Plugs.Ban
    plug GlimeshWeb.Plugs.UserAgent
    plug GlimeshWeb.UniqueUserPlug
    plug NavigationHistory.Tracker, excluded_paths: ["/users/log_in", "/users/register"]
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :graphql_alpha_api do
    plug :accepts, ["json"]
    # This route does not use session / cookies, so CORS can be wide open
    plug GlimeshWeb.Plugs.Cors
    plug :require_alpha_api_header
    plug GlimeshWeb.Plugs.ApiContextPlug
  end

  pipeline :graphql do
    plug :fetch_session
    plug :fetch_current_user
    plug :accepts, ["json"]
    plug GlimeshWeb.Plugs.OldApiContextPlug
  end

  pipeline :oauth do
    # This route does not use session / cookies, so CORS can be wide open
    plug GlimeshWeb.Plugs.Cors
    plug Plug.Parsers, parsers: [:urlendoded]
  end

  if Mix.env() in [:dev, :test] do
    scope "/" do
      pipe_through :browser

      forward "/sent_emails", Bamboo.SentEmailViewerPlug
    end
  end

  scope "/api/oauth", GlimeshWeb do
    pipe_through :oauth

    post "/token", OauthController, :token
    post "/revoke", OauthController, :revoke
    post "/introspect", OauthController, :introspect
  end

  scope "/api/webhook", GlimeshWeb do
    pipe_through :api

    # post "/stripe", WebhookController, :stripe
    post "/taxidpro", WebhookController, :taxidpro
  end

  scope "/api/graph" do
    pipe_through :graphql_alpha_api

    forward "/", Glimesh.Api.GraphiQLPlug,
      schema: Glimesh.Api.Schema,
      socket: GlimeshWeb.GraphApiSocket,
      default_url: {__MODULE__, :graph_default_url},
      socket_url: {__MODULE__, :graph_socket_url},
      interface: :playground,
      analyze_complexity: true,
      max_complexity: 500
  end

  scope "/api" do
    pipe_through :graphql

    forward "/", Absinthe.Plug.GraphiQL,
      schema: Glimesh.OldSchema,
      socket: GlimeshWeb.OldApiSocket,
      default_url: {__MODULE__, :graphiql_default_url},
      socket_url: {__MODULE__, :graphiql_socket_url}
  end

  ## Authentication routes
  scope "/", GlimeshWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    post "/users/log_in_tfa", UserSessionController, :tfa
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", GlimeshWeb do
    pipe_through [:browser, :require_authenticated_user]

    live "/platform_subscriptions", PlatformSubscriptionLive.Index, :index

    get "/users/social/twitter", UserSocialController, :twitter
    delete "/users/social/disconnect/:platform", UserSocialController, :disconnect

    get "/users/payments", UserPaymentsController, :index
    post "/users/payments/setup", UserPaymentsController, :setup
    get "/users/payments/taxes", UserPaymentsController, :taxes
    get "/users/payments/taxes_pending", UserPaymentsController, :taxes_pending
    get "/users/payments/connect", UserPaymentsController, :connect
    put "/users/payments/delete_default_payment", UserPaymentsController, :delete_default_payment

    get "/users/settings/profile", UserSettingsController, :profile
    get "/users/settings/stream", UserSettingsController, :stream

    get "/users/settings/channel_statistics", UserSettingsController, :channel_statistics
    get "/users/settings/addons", UserSettingsController, :addons
    get "/users/settings/emotes", UserSettingsController, :emotes
    get "/users/settings/upload_emotes", UserSettingsController, :upload_emotes
    get "/users/settings/hosting", UserSettingsController, :hosting

    put "/users/settings/create_channel", UserSettingsController, :create_channel
    put "/users/settings/delete_channel", UserSettingsController, :delete_channel
    get "/users/settings/preference", UserSettingsController, :preference
    put "/users/settings/preference", UserSettingsController, :update_preference
    put "/users/settings/update_profile", UserSettingsController, :update_profile
    put "/users/settings/update_channel", UserSettingsController, :update_channel
    get "/users/settings/notifications", UserSettingsController, :notifications

    get "/users/settings/security", UserSecurityController, :index
    put "/users/settings/update_password", UserSecurityController, :update_password
    put "/users/settings/update_email", UserSecurityController, :update_email
    get "/users/settings/confirm_email/:token", UserSecurityController, :confirm_email
    put "/users/settings/update_tfa", UserSecurityController, :update_tfa
    get "/users/settings/get_tfa", UserSecurityController, :get_tfa
    get "/users/settings/tfa_registered", UserSecurityController, :tfa_registered

    put "/users/settings/applications/:id/rotate", UserApplicationsController, :rotate
    resources "/users/settings/applications", UserApplicationsController

    resources "/users/settings/authorizations", UserAuthorizedAppsController,
      only: [:index, :delete],
      param: "id"

    get "/oauth/authorize", OauthController, :authorize
    post "/oauth/authorize", OauthController, :process_authorize
  end

  scope "/", GlimeshWeb do
    pipe_through [:browser, :require_authenticated_user, :require_user_has_channel]

    post "/users/settings/channel/mods/ban_user",
         ChannelModeratorController,
         :ban_user

    delete "/users/settings/channel/mods/unban_user/:username",
           ChannelModeratorController,
           :unban_user

    resources "/users/settings/channel/mods", ChannelModeratorController
  end

  scope "/admin", GlimeshWeb do
    pipe_through [:browser, :require_admin_user]

    import Phoenix.LiveDashboard.Router

    live_dashboard "/phoenix/dashboard", metrics: GlimeshWeb.Telemetry, ecto_repos: [Glimesh.Repo]

    live "/categories", Admin.CategoryLive.Index, :index
    live "/categories/new", Admin.CategoryLive.Index, :new
    live "/categories/:id/edit", Admin.CategoryLive.Index, :edit

    live "/categories/:id", Admin.CategoryLive.Show, :show
    live "/categories/:id/show/edit", Admin.CategoryLive.Show, :edit

    live "/tags", Admin.TagLive.Index, :index
    live "/tags/new", Admin.TagLive.Index, :new
    live "/tags/:id/edit", Admin.TagLive.Index, :edit
  end

  scope "/gct", GlimeshWeb do
    pipe_through [:browser, :require_gct_user]

    get "/", GctController, :index
    get "/me", GctController, :edit_self
    get "/unauthorized", GctController, :unauthorized

    # Lookup scopes
    get "/lookup/user", GctController, :username_lookup
    get "/lookup/channel", GctController, :channel_lookup
    get "/lookup/channel/:channel_id/chat", GctController, :channel_chat_log
    get "/lookup/user/:user_id/chat", GctController, :user_chat_log

    # Editing profile scopes
    get "/edit/profile/:username", GctController, :edit_user_profile
    put "/edit/profile/:username/update", GctController, :update_user_profile

    # Editing user scopes
    get "/edit/:username", GctController, :edit_user
    put "/edit/:username/update", GctController, :update_user

    # Editing channel scopes
    get "/edit/channel/:channel_id", GctController, :edit_channel
    post "/edit/channel/:channel_id/shutdown", GctController, :shutdown_channel
    put "/edit/channel/:channel_id/update", GctController, :update_channel
    put "/edit/channel/:channel_id/delete", GctController, :delete_channel

    # Audit log
    get "/audit-log", GctController, :audit_log

    # Emote scopes
    get "/global-emotes", GctController, :global_emotes
    get "/review-emotes", GctController, :review_emotes

    # Categories and subcategories and tags and probably more
  end

  scope "/", GlimeshWeb do
    pipe_through [:browser, :require_events_team_user]

    live "/eventsteam", EventsTeam.EventsAdminLive, :index
  end

  scope "/", GlimeshWeb do
    pipe_through [:browser]

    get "/about", AboutController, :index
    get "/about/streaming", AboutController, :streaming
    get "/about/team", AboutController, :team
    get "/about/mission", AboutController, :mission
    get "/about/alpha", AboutController, :alpha
    get "/about/faq", AboutController, :faq
    get "/about/privacy", AboutController, :privacy
    get "/about/terms", AboutController, :terms
    get "/about/conduct", AboutController, :conduct
    get "/about/credits", AboutController, :credits
    get "/about/dmca", AboutController, :dmca

    live "/about/open-data", About.OpenDataLive, :index
    live "/about/open-data/subscriptions", About.OpenDataLive, :subscriptions
    live "/about/open-data/streams", About.OpenDataLive, :streams

    get "/events", EventsTeamController, :events_team

    get "/blog", BlogMigrationController, :redirect_blog
    get "/blog/:slug", BlogMigrationController, :redirect_post

    live "/", HomepageLive, :index
    live "/streams", StreamsLive.Index, :index
    live "/streams/following", StreamsLive.Following, :index
    live "/streams/:category", StreamsLive.List, :index

    live "/users", UserLive.Index, :index

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new

lib/glimesh_web/controllers/user_registration_controller.ex
defmodule GlimeshWeb.UserRegistrationController do
  use GlimeshWeb, :controller

  alias Glimesh.Accounts
  alias Glimesh.Accounts.User
  alias GlimeshWeb.UserAuth

  def new(conn, _params) do
    changeset = Accounts.change_user_registration(%User{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"user" => user_params, "h-captcha-response" => captcha_response}) do
    safe_params =
      Map.take(user_params, [
        "username",
        "password",
        "email",
        "allow_glimesh_newsletter_emails"
      ])

    existing_preferences = %Glimesh.Accounts.UserPreference{
      locale: GlimeshWeb.LayoutView.site_locale(conn),
      site_theme: GlimeshWeb.LayoutView.site_theme(conn)
    }

    user_ip = conn.remote_ip |> :inet.ntoa() |> to_string()
    user_params = Map.put(safe_params, "raw_user_ip", user_ip)

    case Hcaptcha.verify(captcha_response) do
      {:ok, _} ->
        case Accounts.register_user(user_params, existing_preferences) do
          {:ok, user} ->
            {:ok, _} =
              Accounts.deliver_user_confirmation_instructions(
                user,
                &Routes.user_confirmation_url(conn, :confirm, &1)
              )

            conn
            |> put_flash(:info, gettext("User created successfully."))
            |> UserAuth.log_in_user(user)

          {:error, %Ecto.Changeset{} = changeset} ->
            render(conn, "new.html", changeset: changeset)
        end

      {:error, _} ->
        conn
        |> put_flash(
          :error,
          gettext("Captcha validation failed, please try again.")
        )
        |> redirect(to: Routes.user_registration_path(conn, :new))
    end
  end

  def create(conn, %{"user" => _}) do
    conn
    |> put_flash(
      :error,
      gettext("Captcha validation failed, please make sure you have JavaScript enabled.")
    )
    |> redirect(to: Routes.user_registration_path(conn, :new))
  end
end

lib/glimesh_web/views/user_registration_view.ex
defmodule GlimeshWeb.UserRegistrationView do
  use GlimeshWeb, :view
end

lib/glimesh_web/templates/user_registration/new.html.eex
<div class="container mt-4">
    <div class="row align-items-center justify-content-md-center">
        <div class="col-md-7 col-lg-5">

            <div class="card">
                <div class="card-body">
                    <h3>Register for our Alpha!</h3>
                    <%= form_for @changeset, Routes.user_registration_path(@conn, :create), fn f -> %>
                    <%= if @changeset.action do %>
                    <div class="alert alert-danger">
                        <p>Oops, something went wrong! Please check the errors below.</p>
                    </div>
                    <% end %>

                    <%= if Application.get_env(:glimesh, :show_staging_warning) do %>
                    <div class="alert alert-danger" role="alert">
                        <strong>Danger!</strong> This is our public TESTING website, all data & streams are FAKE. You
                        can find the real
                        Glimesh at <a href="https://glimesh.tv/">https://glimesh.tv/</a>.
                    </div>
                    <% end %>

                    <p>By creating an account you agree that you have read and acknowledged our
                        <%= link "Terms of Service", to: Routes.about_path(@conn, :terms) %> and
                        <%= link "Privacy Policy", to: Routes.about_path(@conn, :privacy) %>.<br></p>

                    <div class="input-group mt-3 mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fas fa-user fa-fw"></i></span>
                        </div>
                        <%= text_input f, :username, class: "form-control", placeholder: "Username", autofocus: "true", required: true, "aria-label": "Username" %>
                        <%= error_tag f, :username %>
                    </div>

                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fas fa-at fa-fw"></i></span>
                        </div>
                        <%= email_input f, :email, class: "form-control", placeholder: "Email", autofocus: "true", required: true, autocomplete: "username", "aria-label": "Email"  %>
                        <%= error_tag f, :email %>
                    </div>

                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fas fa-lock fa-fw"></i></span>
                        </div>
                        <%= password_input f, :password, class: "form-control", placeholder: "Password", required: true, autocomplete: "new-password", "aria-label": "Password"  %>
                        <%= error_tag f, :password %>
                    </div>

                    <div class="input-group mb-3">
                        <div class="custom-control custom-switch">
                            <%= checkbox f, :allow_glimesh_newsletter_emails, class: "custom-control-input" %>
                            <%= label f, :allow_glimesh_newsletter_emails, gettext("Allow Glimesh Newsletter Emails"), class: "custom-control-label" %>
                            <%= error_tag f, :allow_glimesh_newsletter_emails %>
                            <p> We'll send emails about product launches, upcoming events, or new availability.
                            </p>
                        </div>
                    </div>

                    <div class="text-center">
                        <%= raw Hcaptcha.Template.display(theme: GlimeshWeb.LayoutView.site_theme(@conn)) %>

                        <%= submit "Register", class: "btn btn-primary btn-lg mt-2" %>

                        <div class="mt-4">
                            <%= link "Forgot your password?", to: Routes.user_reset_password_path(@conn, :new) %>
                        </div>
                    </div>

                    <% end %>
                </div>
            </div>

        </div>
        <div class="col-md-5 col-lg-4">
            <h4 class="mt-4">What is Glimesh?</h4>
            <p class="">
                People first streaming, with discoverability as a primary feature. Let's build the next
                generation of streaming. <%= link "Learn More", to: Routes.about_path(@conn, :faq) %>
            </p>
            <h4 class="mt-4">Why register an account?</h4>
            <p>Signing up for a Glimesh account gets you immediate access to engage with your favorite streamers, follow
                the ones you love to stay up to date, and even subscribe to them for support and extra cosmetic perks!
                You can also create a channel and start streaming your own content, with your own chat and
                subscriptions, instantly.
            </p>

            <h5 class="mt-4">Have an account?</h5>
            <%= link "Log in", class: "btn btn-primary", to: Routes.user_session_path(@conn, :new) %>
        </div>
    </div>
</div>